version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres14-mantenimiento
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mantenimiento_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: mantenimiento-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mantenimiento_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["sh", "-c", "echo 'Running migrations...' && sleep 10 && alembic upgrade head && echo 'Migrations complete!' && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 2"]

volumes:
  postgres_data:
